### ISSUE TITLE
Goal for the plugin

### ISSUE THREAD

**Issue by ehrnst** [joatmon08/backstage-plugin-terraform#1]
Hi I am looking for something similar, just for Bicep. And was looking into what the goal for terraform scaffolder action is? Is it to add TF modules to a repo, or deploy resources with TF from Backstage?

**Comment by joatmon08** [comment]
Hi!

This plugin is more exploratory, but the goal for a Terraform scaffolder action involves deploying resources using Terraform Cloud/Enterprise from Backstage.

The actions set up a repository using the built-in action and templates out variables and attributes for a Terraform configuration that can optionally reference a module. Custom actions set up a Terraform Cloud/Enterprise workspace with a VCS connection to the template repository. I thought about doing this all through Backstage, but quickly ran into a question about Day 2 operations on infrastructure. This workflow seems to preserve the IaC approach (allowing break-glass or Day 2 changes using version control) while easing the initial provisioning of Terraform resources.
